"""empty message

Revision ID: 563ed8c2a9aa
Revises: eda9cee14cd0
Create Date: 2026-01-12 20:10:04.088892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '563ed8c2a9aa'
down_revision: Union[str, Sequence[str], None] = 'eda9cee14cd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demo', sa.Column('avatar', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('demo', 'avatar')
    # ### end Alembic commands ###
